### PR TITLE
Sign-in journey content updates

### PR DESCRIPTION
**Pull request by Lloyd-K**
See https://dfedigital.atlassian.net/browse/CPDRP-815?atlOrigin=eyJpIjoiMmQyOWMwMGE3YzAzNDk2Mjk1YTZlYjI4ZTQ4M2VhMDUiLCJwIjoiaiJ9 for details.

### CODE REVIEW

**Comment by Lloyd-K** [comment]
@etheya - I've made the changes requested. Could you re-review please?

**Review by etheya — CHANGES_REQUESTED** [review]
Cant do the list items without hte lead in  paragraph... :-)

**Review by etheya — COMMENTED** [review]
Few broken pages - but fixing them up.

**Comment by Lloyd-K** [comment]
> Cant do the list items without hte lead in paragraph... :-)

I've changed this to a numbered list, no lead-in needed: https://design-system.service.gov.uk/styles/typography/#numbered-lists

**Pull request merged**
